databases:
  - name: smart_ev_db
    databaseName: smart_ev_db
    user: smart_ev_user

services:
  - type: web
    name: smart-ev-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn Smart_EV.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart_ev_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: EMAIL_HOST_USER
        value: vinay.agiletec@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Set this manually in Render dashboard for security
